services:
  web: 
    build: . 
    ports:
      - "8000:8000" 
    volumes:
      - .:/app
    env_file:
      - .env 
    depends_on:
      - db 
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"

  db: 
    image: postgres:16-alpine 
    volumes:
      - pg_data:/var/lib/postgresql/data 
    env_file:
      - .env 
    ports:
      - "5432:5432" 

volumes:
  pg_data: